### ISSUE TITLE
process_basic/nohup.md

### ISSUE THREAD

**Issue by fugr** [tobegit3hub/understand_linux_process#12]
这节的示例里没有使用nohup

**Comment by zuopucuen** [comment]
"它能让进程脱离终端运行，关闭终端后也不会给进程发信号。" 使用nohup后，进程并没有脱离终端，关闭终端时，系统会按照正流程给此终端下得每一个进程发送SIGHUP信号，用nohup启动的进程会忽略这个信号，所以终端推出，进程不会退出。
