### ISSUE TITLE
nohup error

### ISSUE THREAD

**Issue by zuopucuen** [tobegit3hub/understand_linux_process#18]
"它能让进程脱离终端运行，关闭终端后也不会给进程发信号。" 使用nohup后，进程并没有脱离终端，关闭终端时，系统会按照正流程给此终端下的每一个进程发送SIGHUP信号，用nohup启动的进程会忽略这个信号，所以终端退出，进程不会退出。

**Comment by tobegit3hub** [comment]
You're right. I have to edit my description :smiley:

**Comment by tobegit3hub** [comment]
Thanks @zuopucuen for your help :heart:
