### ISSUE TITLE
process_basic/status.md

### ISSUE THREAD

**Issue by Jayce** [tobegit3hub/understand_linux_process#20]
标题: "查看状态"这里的内容编译为html之后显示不正常.

**Comment by tobegit3hub** [comment]
It's ok for me. Did you run `gitbook build` or `gitbook serve`?

**Comment by Jayce** [comment]
访问的http://www.linuxprocess.com/process_basic/status.html
我描述的可能不正确, 我直接贴截图吧, 是显示上的问题. 

**我是用chrome显示内容是这样?**

![image](https://cloud.githubusercontent.com/assets/2687963/5833710/d2871b90-a190-11e4-87df-e6aa337705d2.png)

**不应该是显示成这样么?**

![image](https://cloud.githubusercontent.com/assets/2687963/5833792/b98e7344-a191-11e4-9665-358df9ee1ee2.png)

**Comment by tobegit3hub** [comment]
谢谢提醒，是我的markdown格式不对，马上改过来 :+1:

**Comment by tobegit3hub** [comment]
Resolved by https://github.com/tobegit3hub/understand_linux_process/commit/4eedec0b158d21de357cbd4d68390f876e8d87fe and thanks @Jayce :santa:
