### ISSUE TITLE
一个bash退出码解释的错误

### ISSUE THREAD

**Issue by lihz1990** [tobegit3hub/understand_linux_process#23]
在***进程基础***一章的***退出码***一节的***使用退出码***小节中，第二段：
>当然有意义,我们在写Bash脚本时,可以根据前一个命令的退出码选择是否执行下一个命令。例如安装Run程序的命令	wget
https://raw.githubusercontent.com/runscripts/run/packages/packages/darwin_amd64/run	||	sudo	run	--init	,只有下载脚本成功才会执行后面的安装命令。

在上面的命令中解释中，实际情况是wget执行成功之后，不会执行run，除非wget执行失败，才会执行run！是否应该将||修改为&&？

**Comment by tobegit3hub** [comment]
You're right. Thanks @lihz1990 :+1:
