### ISSUE TITLE
【错别字】进程越多越好？

### ISSUE THREAD

**Issue by ilcc** [tobegit3hub/understand_linux_process#32]
文件：/process_basic/the_more_the_better.md（第18行）

原文：我们想想进程数应该等于CPU数，但是如果进程有阻塞呢？这是是应该提高进程数增加并行数的。

更正：我们想想进程数应该等于CPU数，但是如果进程有阻塞呢？这**时**是应该提高进程数增加并行数的。

**Comment by tobegit3hub** [comment]
Nice catch @ilcc :+1:
