### ISSUE TITLE
Typo in spawn

### ISSUE THREAD

**Issue by ilcc** [tobegit3hub/understand_linux_process#34]
File: /go_example/spawn.md (Line 6)

Original: 它能够执行任意Go或者非Go程序，并且等待放回结果，外部进程结束后继续执行本程序。

Revise: 它能够执行任意Go或者非Go程序，并且等待**返**回结果，外部进程结束后继续执行本程序。

**Comment by tobegit3hub** [comment]
Thanks @ilcc for your correction :smiley:
