### ISSUE TITLE
Several typos

### ISSUE THREAD

**Issue by ilcc** [tobegit3hub/understand_linux_process#35]
1. /process_advanced/ipc.md (Line 26)

 Original: 套接口(Socket)

 Revised: 套接**字**(Socket)

2. /process_advanced/system_call.md (Line 4)

 Original: 开发者运行得进程运行在用户态(todo: user space)

 Revised: 开发者运行**的**进程运行在用户态(todo: user space)

3. /process_advanced/namespaces.md (Line12)

 Original: 创建进程时使用`clone`取代`fork`即刻创建同一命名空间下的进程。

 Revised: 创建进程时使用`clone`取代`fork`即**可**创建同一命名空间下的进程。

4. /reference/README.md (Line 4)

 Original: 最后一章列举本文参考的过的书籍和项目

 Revised: 最后一章列举本文参考**~~的~~**过的书籍和项目

5. /process_advanced/fd.md (Line 18)

 Original: 我们网上看到配置`ulimit`也是为了调大系统的打开文件个数

 Revised: 我们网上看到配置`ulimit`也是为了调**整**系统的打开文件个数

6. /process_basic/posix.md (Line 18)

 Original: 这是非常严谨的文档，感兴趣的同学可以读下，对普通的程序员我们还是以下的内容。

 Revised: 这是非常严谨的文档，感兴趣的同学可以读下，对普通的程序员我们还是**建议了解**以下的内容。

7. /process_advanced/file_lock.md (Line 14)

 Original: 这样我们很容易可以实和读锁，但是所有流程都需要自己控制。

 Revised: 这样我们很容易可以**实现【待修改】**读锁，但是所有流程都需要自己控制。

**Comment by tobegit3hub** [comment]
I have to say I'm sorry to leave so many typos. And @ilcc you're doing the great job to help me out. Thanks a lot :+1:

**Comment by tobegit3hub** [comment]
Fix by https://github.com/tobegit3hub/understand_linux_process/commit/ccb26bf9342c718667eb5a1feae969614514bb59
