### ISSUE TITLE
some typos in project_run/architecture.md

### ISSUE THREAD

**Issue by shwley** [tobegit3hub/understand_linux_process#37]
[project_run/architecture.md](https://github.com/tobegit3hub/understand_linux_process/blob/master/project_run/architecture.md)中的最后一句：
- 这样前一个命令有可以使用旧脚本也可能使用新脚本，这需我们规避这样的问题。

应为
- 这样前一个命令有可**能**使用旧脚本也可能使用新脚本，这**是**我们规避这样的问题。

Thanks for sharing ~

**Comment by tobegit3hub** [comment]
Nice catch @shwley and thanks for your reporting.
