### ISSUE TITLE
http://www.linuxprocess.com/ 的静态资源加速

### ISSUE THREAD

**Issue by alsotang** [tobegit3hub/understand_linux_process#40]
http://su.baidu.com/

http://www.linuxprocess.com/ 是个非 https 的网站，可以考虑接入百度云加速。这样图片载入速度就会快多了。百度云加速会使用香港节点为网站加速。

**Comment by tobegit3hub** [comment]
This is deployed on gitbook server. I don't think we should migrate to baidu cloud service.

Anyway, thanks for your suggestions. @alsotang

**Comment by alsotang** [comment]
alright, but in mainland china, picture loading speed is indeed slow.
