### ISSUE TITLE
1.10进程越多越好错别字

### ISSUE THREAD

**Issue by an9er** [tobegit3hub/understand_linux_process#42]
>特殊情况
>
>我们想想进程数应该等于CPU数，但是如果进程有阻塞呢？这`是`是应该提高进程数增加并行数的

第一个‘是’是否应该是‘时’。

：）

**Comment by tobegit3hub** [comment]
Thanks @an9er and this has been fixed before. Please checkout this https://github.com/tobegit3hub/understand_linux_process/blame/master/process_basic/the_more_the_better.md#L18
